// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockeryEndpoint creates a new instance of MockeryEndpoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockeryEndpoint[ID comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockeryEndpoint[ID] {
	mock := &MockeryEndpoint[ID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockeryEndpoint is an autogenerated mock type for the Endpoint type
type MockeryEndpoint[ID comparable] struct {
	mock.Mock
}

type MockeryEndpoint_Expecter[ID comparable] struct {
	mock *mock.Mock
}

func (_m *MockeryEndpoint[ID]) EXPECT() *MockeryEndpoint_Expecter[ID] {
	return &MockeryEndpoint_Expecter[ID]{mock: &_m.Mock}
}

// Activate provides a mock function for the type MockeryEndpoint
func (_mock *MockeryEndpoint[ID]) Activate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockeryEndpoint_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockeryEndpoint_Activate_Call[ID comparable] struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockeryEndpoint_Expecter[ID]) Activate(ctx interface{}) *MockeryEndpoint_Activate_Call[ID] {
	return &MockeryEndpoint_Activate_Call[ID]{Call: _e.mock.On("Activate", ctx)}
}

func (_c *MockeryEndpoint_Activate_Call[ID]) Run(run func(ctx context.Context)) *MockeryEndpoint_Activate_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryEndpoint_Activate_Call[ID]) Return(err error) *MockeryEndpoint_Activate_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockeryEndpoint_Activate_Call[ID]) RunAndReturn(run func(ctx context.Context) error) *MockeryEndpoint_Activate_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockeryEndpoint
func (_mock *MockeryEndpoint[ID]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockeryEndpoint_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockeryEndpoint_Close_Call[ID comparable] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockeryEndpoint_Expecter[ID]) Close(ctx interface{}) *MockeryEndpoint_Close_Call[ID] {
	return &MockeryEndpoint_Close_Call[ID]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockeryEndpoint_Close_Call[ID]) Run(run func(ctx context.Context)) *MockeryEndpoint_Close_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryEndpoint_Close_Call[ID]) Return(err error) *MockeryEndpoint_Close_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockeryEndpoint_Close_Call[ID]) RunAndReturn(run func(ctx context.Context) error) *MockeryEndpoint_Close_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockeryEndpoint
func (_mock *MockeryEndpoint[ID]) ID() ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 ID
	if returnFunc, ok := ret.Get(0).(func() ID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ID)
		}
	}
	return r0
}

// MockeryEndpoint_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockeryEndpoint_ID_Call[ID comparable] struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockeryEndpoint_Expecter[ID]) ID() *MockeryEndpoint_ID_Call[ID] {
	return &MockeryEndpoint_ID_Call[ID]{Call: _e.mock.On("ID")}
}

func (_c *MockeryEndpoint_ID_Call[ID]) Run(run func()) *MockeryEndpoint_ID_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockeryEndpoint_ID_Call[ID]) Return(v ID) *MockeryEndpoint_ID_Call[ID] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockeryEndpoint_ID_Call[ID]) RunAndReturn(run func() ID) *MockeryEndpoint_ID_Call[ID] {
	_c.Call.Return(run)
	return _c
}
