// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	"github.com/samber/mo"
	mock "github.com/stretchr/testify/mock"
	"github.com/yeluyang/gopkg/flow/interfaces"
)

// NewMockeryMessage creates a new instance of MockeryMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockeryMessage[Seq comparable, SinkID comparable, Visitor any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockeryMessage[Seq, SinkID, Visitor] {
	mock := &MockeryMessage[Seq, SinkID, Visitor]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockeryMessage is an autogenerated mock type for the Message type
type MockeryMessage[Seq comparable, SinkID comparable, Visitor any] struct {
	mock.Mock
}

type MockeryMessage_Expecter[Seq comparable, SinkID comparable, Visitor any] struct {
	mock *mock.Mock
}

func (_m *MockeryMessage[Seq, SinkID, Visitor]) EXPECT() *MockeryMessage_Expecter[Seq, SinkID, Visitor] {
	return &MockeryMessage_Expecter[Seq, SinkID, Visitor]{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[Seq, SinkID, Visitor]) Accept(ctx context.Context, visitor Visitor) ([]interfaces.Message[Seq, SinkID, Visitor], error) {
	ret := _mock.Called(ctx, visitor)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 []interfaces.Message[Seq, SinkID, Visitor]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Visitor) ([]interfaces.Message[Seq, SinkID, Visitor], error)); ok {
		return returnFunc(ctx, visitor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Visitor) []interfaces.Message[Seq, SinkID, Visitor]); ok {
		r0 = returnFunc(ctx, visitor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Message[Seq, SinkID, Visitor])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Visitor) error); ok {
		r1 = returnFunc(ctx, visitor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockeryMessage_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockeryMessage_Accept_Call[Seq comparable, SinkID comparable, Visitor any] struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - visitor Visitor
func (_e *MockeryMessage_Expecter[Seq, SinkID, Visitor]) Accept(ctx interface{}, visitor interface{}) *MockeryMessage_Accept_Call[Seq, SinkID, Visitor] {
	return &MockeryMessage_Accept_Call[Seq, SinkID, Visitor]{Call: _e.mock.On("Accept", ctx, visitor)}
}

func (_c *MockeryMessage_Accept_Call[Seq, SinkID, Visitor]) Run(run func(ctx context.Context, visitor Visitor)) *MockeryMessage_Accept_Call[Seq, SinkID, Visitor] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Visitor
		if args[1] != nil {
			arg1 = args[1].(Visitor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockeryMessage_Accept_Call[Seq, SinkID, Visitor]) Return(messages []interfaces.Message[Seq, SinkID, Visitor], err error) *MockeryMessage_Accept_Call[Seq, SinkID, Visitor] {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockeryMessage_Accept_Call[Seq, SinkID, Visitor]) RunAndReturn(run func(ctx context.Context, visitor Visitor) ([]interfaces.Message[Seq, SinkID, Visitor], error)) *MockeryMessage_Accept_Call[Seq, SinkID, Visitor] {
	_c.Call.Return(run)
	return _c
}

// DrainTo provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[Seq, SinkID, Visitor]) DrainTo() mo.Option[SinkID] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DrainTo")
	}

	var r0 mo.Option[SinkID]
	if returnFunc, ok := ret.Get(0).(func() mo.Option[SinkID]); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(mo.Option[SinkID])
	}
	return r0
}

// MockeryMessage_DrainTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DrainTo'
type MockeryMessage_DrainTo_Call[Seq comparable, SinkID comparable, Visitor any] struct {
	*mock.Call
}

// DrainTo is a helper method to define mock.On call
func (_e *MockeryMessage_Expecter[Seq, SinkID, Visitor]) DrainTo() *MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor] {
	return &MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor]{Call: _e.mock.On("DrainTo")}
}

func (_c *MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor]) Run(run func()) *MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor]) Return(option mo.Option[SinkID]) *MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor] {
	_c.Call.Return(option)
	return _c
}

func (_c *MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor]) RunAndReturn(run func() mo.Option[SinkID]) *MockeryMessage_DrainTo_Call[Seq, SinkID, Visitor] {
	_c.Call.Return(run)
	return _c
}

// Sequence provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[Seq, SinkID, Visitor]) Sequence() Seq {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sequence")
	}

	var r0 Seq
	if returnFunc, ok := ret.Get(0).(func() Seq); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Seq)
		}
	}
	return r0
}

// MockeryMessage_Sequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sequence'
type MockeryMessage_Sequence_Call[Seq comparable, SinkID comparable, Visitor any] struct {
	*mock.Call
}

// Sequence is a helper method to define mock.On call
func (_e *MockeryMessage_Expecter[Seq, SinkID, Visitor]) Sequence() *MockeryMessage_Sequence_Call[Seq, SinkID, Visitor] {
	return &MockeryMessage_Sequence_Call[Seq, SinkID, Visitor]{Call: _e.mock.On("Sequence")}
}

func (_c *MockeryMessage_Sequence_Call[Seq, SinkID, Visitor]) Run(run func()) *MockeryMessage_Sequence_Call[Seq, SinkID, Visitor] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockeryMessage_Sequence_Call[Seq, SinkID, Visitor]) Return(v Seq) *MockeryMessage_Sequence_Call[Seq, SinkID, Visitor] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockeryMessage_Sequence_Call[Seq, SinkID, Visitor]) RunAndReturn(run func() Seq) *MockeryMessage_Sequence_Call[Seq, SinkID, Visitor] {
	_c.Call.Return(run)
	return _c
}
