// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockerySink creates a new instance of MockerySink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockerySink[SinkID comparable, Msg any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockerySink[SinkID, Msg] {
	mock := &MockerySink[SinkID, Msg]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockerySink is an autogenerated mock type for the Sink type
type MockerySink[SinkID comparable, Msg any] struct {
	mock.Mock
}

type MockerySink_Expecter[SinkID comparable, Msg any] struct {
	mock *mock.Mock
}

func (_m *MockerySink[SinkID, Msg]) EXPECT() *MockerySink_Expecter[SinkID, Msg] {
	return &MockerySink_Expecter[SinkID, Msg]{mock: &_m.Mock}
}

// Drain provides a mock function for the type MockerySink
func (_mock *MockerySink[SinkID, Msg]) Drain(ctx context.Context, msg []Msg) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []Msg) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockerySink_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type MockerySink_Drain_Call[SinkID comparable, Msg any] struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
//   - ctx context.Context
//   - msg []Msg
func (_e *MockerySink_Expecter[SinkID, Msg]) Drain(ctx interface{}, msg interface{}) *MockerySink_Drain_Call[SinkID, Msg] {
	return &MockerySink_Drain_Call[SinkID, Msg]{Call: _e.mock.On("Drain", ctx, msg)}
}

func (_c *MockerySink_Drain_Call[SinkID, Msg]) Run(run func(ctx context.Context, msg []Msg)) *MockerySink_Drain_Call[SinkID, Msg] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []Msg
		if args[1] != nil {
			arg1 = args[1].([]Msg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockerySink_Drain_Call[SinkID, Msg]) Return(err error) *MockerySink_Drain_Call[SinkID, Msg] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockerySink_Drain_Call[SinkID, Msg]) RunAndReturn(run func(ctx context.Context, msg []Msg) error) *MockerySink_Drain_Call[SinkID, Msg] {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockerySink
func (_mock *MockerySink[SinkID, Msg]) ID() SinkID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 SinkID
	if returnFunc, ok := ret.Get(0).(func() SinkID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SinkID)
		}
	}
	return r0
}

// MockerySink_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockerySink_ID_Call[SinkID comparable, Msg any] struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockerySink_Expecter[SinkID, Msg]) ID() *MockerySink_ID_Call[SinkID, Msg] {
	return &MockerySink_ID_Call[SinkID, Msg]{Call: _e.mock.On("ID")}
}

func (_c *MockerySink_ID_Call[SinkID, Msg]) Run(run func()) *MockerySink_ID_Call[SinkID, Msg] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockerySink_ID_Call[SinkID, Msg]) Return(v SinkID) *MockerySink_ID_Call[SinkID, Msg] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockerySink_ID_Call[SinkID, Msg]) RunAndReturn(run func() SinkID) *MockerySink_ID_Call[SinkID, Msg] {
	_c.Call.Return(run)
	return _c
}
