// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yeluyang/gopkg/flow/interfaces"
)

// NewMockerySink creates a new instance of MockerySink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockerySink[E comparable, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockerySink[E, V] {
	mock := &MockerySink[E, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockerySink is an autogenerated mock type for the Sink type
type MockerySink[E comparable, V any] struct {
	mock.Mock
}

type MockerySink_Expecter[E comparable, V any] struct {
	mock *mock.Mock
}

func (_m *MockerySink[E, V]) EXPECT() *MockerySink_Expecter[E, V] {
	return &MockerySink_Expecter[E, V]{mock: &_m.Mock}
}

// Activate provides a mock function for the type MockerySink
func (_mock *MockerySink[E, V]) Activate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockerySink_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockerySink_Activate_Call[E comparable, V any] struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockerySink_Expecter[E, V]) Activate(ctx interface{}) *MockerySink_Activate_Call[E, V] {
	return &MockerySink_Activate_Call[E, V]{Call: _e.mock.On("Activate", ctx)}
}

func (_c *MockerySink_Activate_Call[E, V]) Run(run func(ctx context.Context)) *MockerySink_Activate_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockerySink_Activate_Call[E, V]) Return(err error) *MockerySink_Activate_Call[E, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockerySink_Activate_Call[E, V]) RunAndReturn(run func(ctx context.Context) error) *MockerySink_Activate_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockerySink
func (_mock *MockerySink[E, V]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockerySink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockerySink_Close_Call[E comparable, V any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockerySink_Expecter[E, V]) Close(ctx interface{}) *MockerySink_Close_Call[E, V] {
	return &MockerySink_Close_Call[E, V]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockerySink_Close_Call[E, V]) Run(run func(ctx context.Context)) *MockerySink_Close_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockerySink_Close_Call[E, V]) Return(err error) *MockerySink_Close_Call[E, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockerySink_Close_Call[E, V]) RunAndReturn(run func(ctx context.Context) error) *MockerySink_Close_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// Drain provides a mock function for the type MockerySink
func (_mock *MockerySink[E, V]) Drain(ctx context.Context, msg []interfaces.Message[E, V]) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interfaces.Message[E, V]) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockerySink_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type MockerySink_Drain_Call[E comparable, V any] struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
//   - ctx context.Context
//   - msg []interfaces.Message[E, V]
func (_e *MockerySink_Expecter[E, V]) Drain(ctx interface{}, msg interface{}) *MockerySink_Drain_Call[E, V] {
	return &MockerySink_Drain_Call[E, V]{Call: _e.mock.On("Drain", ctx, msg)}
}

func (_c *MockerySink_Drain_Call[E, V]) Run(run func(ctx context.Context, msg []interfaces.Message[E, V])) *MockerySink_Drain_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []interfaces.Message[E, V]
		if args[1] != nil {
			arg1 = args[1].([]interfaces.Message[E, V])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockerySink_Drain_Call[E, V]) Return(err error) *MockerySink_Drain_Call[E, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockerySink_Drain_Call[E, V]) RunAndReturn(run func(ctx context.Context, msg []interfaces.Message[E, V]) error) *MockerySink_Drain_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockerySink
func (_mock *MockerySink[E, V]) ID() E {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 E
	if returnFunc, ok := ret.Get(0).(func() E); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(E)
		}
	}
	return r0
}

// MockerySink_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockerySink_ID_Call[E comparable, V any] struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockerySink_Expecter[E, V]) ID() *MockerySink_ID_Call[E, V] {
	return &MockerySink_ID_Call[E, V]{Call: _e.mock.On("ID")}
}

func (_c *MockerySink_ID_Call[E, V]) Run(run func()) *MockerySink_ID_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockerySink_ID_Call[E, V]) Return(v E) *MockerySink_ID_Call[E, V] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockerySink_ID_Call[E, V]) RunAndReturn(run func() E) *MockerySink_ID_Call[E, V] {
	_c.Call.Return(run)
	return _c
}
