// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yeluyang/gopkg/flow/interfaces"
)

// NewMockeryDuplex creates a new instance of MockeryDuplex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockeryDuplex[E comparable, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockeryDuplex[E, V] {
	mock := &MockeryDuplex[E, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockeryDuplex is an autogenerated mock type for the Duplex type
type MockeryDuplex[E comparable, V any] struct {
	mock.Mock
}

type MockeryDuplex_Expecter[E comparable, V any] struct {
	mock *mock.Mock
}

func (_m *MockeryDuplex[E, V]) EXPECT() *MockeryDuplex_Expecter[E, V] {
	return &MockeryDuplex_Expecter[E, V]{mock: &_m.Mock}
}

// Activate provides a mock function for the type MockeryDuplex
func (_mock *MockeryDuplex[E, V]) Activate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockeryDuplex_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockeryDuplex_Activate_Call[E comparable, V any] struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockeryDuplex_Expecter[E, V]) Activate(ctx interface{}) *MockeryDuplex_Activate_Call[E, V] {
	return &MockeryDuplex_Activate_Call[E, V]{Call: _e.mock.On("Activate", ctx)}
}

func (_c *MockeryDuplex_Activate_Call[E, V]) Run(run func(ctx context.Context)) *MockeryDuplex_Activate_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryDuplex_Activate_Call[E, V]) Return(err error) *MockeryDuplex_Activate_Call[E, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockeryDuplex_Activate_Call[E, V]) RunAndReturn(run func(ctx context.Context) error) *MockeryDuplex_Activate_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockeryDuplex
func (_mock *MockeryDuplex[E, V]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockeryDuplex_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockeryDuplex_Close_Call[E comparable, V any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockeryDuplex_Expecter[E, V]) Close(ctx interface{}) *MockeryDuplex_Close_Call[E, V] {
	return &MockeryDuplex_Close_Call[E, V]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockeryDuplex_Close_Call[E, V]) Run(run func(ctx context.Context)) *MockeryDuplex_Close_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryDuplex_Close_Call[E, V]) Return(err error) *MockeryDuplex_Close_Call[E, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockeryDuplex_Close_Call[E, V]) RunAndReturn(run func(ctx context.Context) error) *MockeryDuplex_Close_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// Drain provides a mock function for the type MockeryDuplex
func (_mock *MockeryDuplex[E, V]) Drain(ctx context.Context, msg []interfaces.Message[E, V]) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interfaces.Message[E, V]) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockeryDuplex_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type MockeryDuplex_Drain_Call[E comparable, V any] struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
//   - ctx context.Context
//   - msg []interfaces.Message[E, V]
func (_e *MockeryDuplex_Expecter[E, V]) Drain(ctx interface{}, msg interface{}) *MockeryDuplex_Drain_Call[E, V] {
	return &MockeryDuplex_Drain_Call[E, V]{Call: _e.mock.On("Drain", ctx, msg)}
}

func (_c *MockeryDuplex_Drain_Call[E, V]) Run(run func(ctx context.Context, msg []interfaces.Message[E, V])) *MockeryDuplex_Drain_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []interfaces.Message[E, V]
		if args[1] != nil {
			arg1 = args[1].([]interfaces.Message[E, V])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockeryDuplex_Drain_Call[E, V]) Return(err error) *MockeryDuplex_Drain_Call[E, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockeryDuplex_Drain_Call[E, V]) RunAndReturn(run func(ctx context.Context, msg []interfaces.Message[E, V]) error) *MockeryDuplex_Drain_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockeryDuplex
func (_mock *MockeryDuplex[E, V]) ID() E {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 E
	if returnFunc, ok := ret.Get(0).(func() E); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(E)
		}
	}
	return r0
}

// MockeryDuplex_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockeryDuplex_ID_Call[E comparable, V any] struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockeryDuplex_Expecter[E, V]) ID() *MockeryDuplex_ID_Call[E, V] {
	return &MockeryDuplex_ID_Call[E, V]{Call: _e.mock.On("ID")}
}

func (_c *MockeryDuplex_ID_Call[E, V]) Run(run func()) *MockeryDuplex_ID_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockeryDuplex_ID_Call[E, V]) Return(v E) *MockeryDuplex_ID_Call[E, V] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockeryDuplex_ID_Call[E, V]) RunAndReturn(run func() E) *MockeryDuplex_ID_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockeryDuplex
func (_mock *MockeryDuplex[E, V]) Next(ctx context.Context) ([]interfaces.Message[E, V], bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 []interfaces.Message[E, V]
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]interfaces.Message[E, V], bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []interfaces.Message[E, V]); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Message[E, V])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockeryDuplex_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockeryDuplex_Next_Call[E comparable, V any] struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockeryDuplex_Expecter[E, V]) Next(ctx interface{}) *MockeryDuplex_Next_Call[E, V] {
	return &MockeryDuplex_Next_Call[E, V]{Call: _e.mock.On("Next", ctx)}
}

func (_c *MockeryDuplex_Next_Call[E, V]) Run(run func(ctx context.Context)) *MockeryDuplex_Next_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryDuplex_Next_Call[E, V]) Return(messages []interfaces.Message[E, V], b bool, err error) *MockeryDuplex_Next_Call[E, V] {
	_c.Call.Return(messages, b, err)
	return _c
}

func (_c *MockeryDuplex_Next_Call[E, V]) RunAndReturn(run func(ctx context.Context) ([]interfaces.Message[E, V], bool, error)) *MockeryDuplex_Next_Call[E, V] {
	_c.Call.Return(run)
	return _c
}
