// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockeryinlet creates a new instance of mockeryinlet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockeryinlet[Msg any](t interface {
	mock.TestingT
	Cleanup(func())
}) *mockeryinlet[Msg] {
	mock := &mockeryinlet[Msg]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockeryinlet is an autogenerated mock type for the inlet type
type mockeryinlet[Msg any] struct {
	mock.Mock
}

type mockeryinlet_Expecter[Msg any] struct {
	mock *mock.Mock
}

func (_m *mockeryinlet[Msg]) EXPECT() *mockeryinlet_Expecter[Msg] {
	return &mockeryinlet_Expecter[Msg]{mock: &_m.Mock}
}

// Next provides a mock function for the type mockeryinlet
func (_mock *mockeryinlet[Msg]) Next(ctx context.Context) ([]Msg, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 []Msg
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Msg, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Msg); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Msg)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockeryinlet_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type mockeryinlet_Next_Call[Msg any] struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockeryinlet_Expecter[Msg]) Next(ctx interface{}) *mockeryinlet_Next_Call[Msg] {
	return &mockeryinlet_Next_Call[Msg]{Call: _e.mock.On("Next", ctx)}
}

func (_c *mockeryinlet_Next_Call[Msg]) Run(run func(ctx context.Context)) *mockeryinlet_Next_Call[Msg] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockeryinlet_Next_Call[Msg]) Return(vs []Msg, b bool, err error) *mockeryinlet_Next_Call[Msg] {
	_c.Call.Return(vs, b, err)
	return _c
}

func (_c *mockeryinlet_Next_Call[Msg]) RunAndReturn(run func(ctx context.Context) ([]Msg, bool, error)) *mockeryinlet_Next_Call[Msg] {
	_c.Call.Return(run)
	return _c
}
