// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockeryoutlet creates a new instance of mockeryoutlet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockeryoutlet[Msg any](t interface {
	mock.TestingT
	Cleanup(func())
}) *mockeryoutlet[Msg] {
	mock := &mockeryoutlet[Msg]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockeryoutlet is an autogenerated mock type for the outlet type
type mockeryoutlet[Msg any] struct {
	mock.Mock
}

type mockeryoutlet_Expecter[Msg any] struct {
	mock *mock.Mock
}

func (_m *mockeryoutlet[Msg]) EXPECT() *mockeryoutlet_Expecter[Msg] {
	return &mockeryoutlet_Expecter[Msg]{mock: &_m.Mock}
}

// Drain provides a mock function for the type mockeryoutlet
func (_mock *mockeryoutlet[Msg]) Drain(ctx context.Context, msg []Msg) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []Msg) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockeryoutlet_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type mockeryoutlet_Drain_Call[Msg any] struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
//   - ctx context.Context
//   - msg []Msg
func (_e *mockeryoutlet_Expecter[Msg]) Drain(ctx interface{}, msg interface{}) *mockeryoutlet_Drain_Call[Msg] {
	return &mockeryoutlet_Drain_Call[Msg]{Call: _e.mock.On("Drain", ctx, msg)}
}

func (_c *mockeryoutlet_Drain_Call[Msg]) Run(run func(ctx context.Context, msg []Msg)) *mockeryoutlet_Drain_Call[Msg] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []Msg
		if args[1] != nil {
			arg1 = args[1].([]Msg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockeryoutlet_Drain_Call[Msg]) Return(err error) *mockeryoutlet_Drain_Call[Msg] {
	_c.Call.Return(err)
	return _c
}

func (_c *mockeryoutlet_Drain_Call[Msg]) RunAndReturn(run func(ctx context.Context, msg []Msg) error) *mockeryoutlet_Drain_Call[Msg] {
	_c.Call.Return(run)
	return _c
}
