// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yeluyang/gopkg/flow/interfaces"
)

// NewMockeryMessage creates a new instance of MockeryMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockeryMessage[E comparable, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockeryMessage[E, V] {
	mock := &MockeryMessage[E, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockeryMessage is an autogenerated mock type for the Message type
type MockeryMessage[E comparable, V any] struct {
	mock.Mock
}

type MockeryMessage_Expecter[E comparable, V any] struct {
	mock *mock.Mock
}

func (_m *MockeryMessage[E, V]) EXPECT() *MockeryMessage_Expecter[E, V] {
	return &MockeryMessage_Expecter[E, V]{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[E, V]) Accept(ctx context.Context, visitor V) ([]interfaces.Message[E, V], error) {
	ret := _mock.Called(ctx, visitor)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 []interfaces.Message[E, V]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, V) ([]interfaces.Message[E, V], error)); ok {
		return returnFunc(ctx, visitor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, V) []interfaces.Message[E, V]); ok {
		r0 = returnFunc(ctx, visitor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Message[E, V])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, V) error); ok {
		r1 = returnFunc(ctx, visitor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockeryMessage_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockeryMessage_Accept_Call[E comparable, V any] struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - visitor V
func (_e *MockeryMessage_Expecter[E, V]) Accept(ctx interface{}, visitor interface{}) *MockeryMessage_Accept_Call[E, V] {
	return &MockeryMessage_Accept_Call[E, V]{Call: _e.mock.On("Accept", ctx, visitor)}
}

func (_c *MockeryMessage_Accept_Call[E, V]) Run(run func(ctx context.Context, visitor V)) *MockeryMessage_Accept_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 V
		if args[1] != nil {
			arg1 = args[1].(V)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockeryMessage_Accept_Call[E, V]) Return(messages []interfaces.Message[E, V], err error) *MockeryMessage_Accept_Call[E, V] {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockeryMessage_Accept_Call[E, V]) RunAndReturn(run func(ctx context.Context, visitor V) ([]interfaces.Message[E, V], error)) *MockeryMessage_Accept_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// Activate provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[E, V]) Activate(ctx context.Context) []E {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 []E
	if returnFunc, ok := ret.Get(0).(func(context.Context) []E); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]E)
		}
	}
	return r0
}

// MockeryMessage_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockeryMessage_Activate_Call[E comparable, V any] struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockeryMessage_Expecter[E, V]) Activate(ctx interface{}) *MockeryMessage_Activate_Call[E, V] {
	return &MockeryMessage_Activate_Call[E, V]{Call: _e.mock.On("Activate", ctx)}
}

func (_c *MockeryMessage_Activate_Call[E, V]) Run(run func(ctx context.Context)) *MockeryMessage_Activate_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryMessage_Activate_Call[E, V]) Return(vs []E) *MockeryMessage_Activate_Call[E, V] {
	_c.Call.Return(vs)
	return _c
}

func (_c *MockeryMessage_Activate_Call[E, V]) RunAndReturn(run func(ctx context.Context) []E) *MockeryMessage_Activate_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// DrainTo provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[E, V]) DrainTo(ctx context.Context) []E {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DrainTo")
	}

	var r0 []E
	if returnFunc, ok := ret.Get(0).(func(context.Context) []E); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]E)
		}
	}
	return r0
}

// MockeryMessage_DrainTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DrainTo'
type MockeryMessage_DrainTo_Call[E comparable, V any] struct {
	*mock.Call
}

// DrainTo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockeryMessage_Expecter[E, V]) DrainTo(ctx interface{}) *MockeryMessage_DrainTo_Call[E, V] {
	return &MockeryMessage_DrainTo_Call[E, V]{Call: _e.mock.On("DrainTo", ctx)}
}

func (_c *MockeryMessage_DrainTo_Call[E, V]) Run(run func(ctx context.Context)) *MockeryMessage_DrainTo_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryMessage_DrainTo_Call[E, V]) Return(vs []E) *MockeryMessage_DrainTo_Call[E, V] {
	_c.Call.Return(vs)
	return _c
}

func (_c *MockeryMessage_DrainTo_Call[E, V]) RunAndReturn(run func(ctx context.Context) []E) *MockeryMessage_DrainTo_Call[E, V] {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[E, V]) Options() []interfaces.Option {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 []interfaces.Option
	if returnFunc, ok := ret.Get(0).(func() []interfaces.Option); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Option)
		}
	}
	return r0
}

// MockeryMessage_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockeryMessage_Options_Call[E comparable, V any] struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
func (_e *MockeryMessage_Expecter[E, V]) Options() *MockeryMessage_Options_Call[E, V] {
	return &MockeryMessage_Options_Call[E, V]{Call: _e.mock.On("Options")}
}

func (_c *MockeryMessage_Options_Call[E, V]) Run(run func()) *MockeryMessage_Options_Call[E, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockeryMessage_Options_Call[E, V]) Return(options []interfaces.Option) *MockeryMessage_Options_Call[E, V] {
	_c.Call.Return(options)
	return _c
}

func (_c *MockeryMessage_Options_Call[E, V]) RunAndReturn(run func() []interfaces.Option) *MockeryMessage_Options_Call[E, V] {
	_c.Call.Return(run)
	return _c
}
