// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/yeluyang/gopkg/flow/interfaces"
)

// NewMockeryOption creates a new instance of MockeryOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockeryOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockeryOption {
	mock := &MockeryOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockeryOption is an autogenerated mock type for the Option type
type MockeryOption struct {
	mock.Mock
}

type MockeryOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockeryOption) EXPECT() *MockeryOption_Expecter {
	return &MockeryOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type MockeryOption
func (_mock *MockeryOption) apply(msgConfig *interfaces.MsgConfig) {
	_mock.Called(msgConfig)
	return
}

// MockeryOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockeryOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - msgConfig *interfaces.MsgConfig
func (_e *MockeryOption_Expecter) apply(msgConfig interface{}) *MockeryOption_apply_Call {
	return &MockeryOption_apply_Call{Call: _e.mock.On("apply", msgConfig)}
}

func (_c *MockeryOption_apply_Call) Run(run func(msgConfig *interfaces.MsgConfig)) *MockeryOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *interfaces.MsgConfig
		if args[0] != nil {
			arg0 = args[0].(*interfaces.MsgConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockeryOption_apply_Call) Return() *MockeryOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockeryOption_apply_Call) RunAndReturn(run func(msgConfig *interfaces.MsgConfig)) *MockeryOption_apply_Call {
	_c.Run(run)
	return _c
}
