// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSink creates a new instance of Sink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSink[M any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Sink[M] {
	mock := &Sink[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sink is an autogenerated mock type for the Sink type
type Sink[M any] struct {
	mock.Mock
}

type Sink_Expecter[M any] struct {
	mock *mock.Mock
}

func (_m *Sink[M]) EXPECT() *Sink_Expecter[M] {
	return &Sink_Expecter[M]{mock: &_m.Mock}
}

// Drain provides a mock function for the type Sink
func (_mock *Sink[M]) Drain(ctx context.Context, msgs ...M) error {
	var tmpRet mock.Arguments
	if len(msgs) > 0 {
		tmpRet = _mock.Called(ctx, msgs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...M) error); ok {
		r0 = returnFunc(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Sink_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type Sink_Drain_Call[M any] struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...M
func (_e *Sink_Expecter[M]) Drain(ctx any, msgs ...any) *Sink_Drain_Call[M] {
	return &Sink_Drain_Call[M]{Call: _e.mock.On("Drain",
		append([]any{ctx}, msgs...)...)}
}

func (_c *Sink_Drain_Call[M]) Run(run func(ctx context.Context, msgs ...M)) *Sink_Drain_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []M
		var variadicArgs []M
		if len(args) > 1 {
			variadicArgs = args[1].([]M)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Sink_Drain_Call[M]) Return(err error) *Sink_Drain_Call[M] {
	_c.Call.Return(err)
	return _c
}

func (_c *Sink_Drain_Call[M]) RunAndReturn(run func(ctx context.Context, msgs ...M) error) *Sink_Drain_Call[M] {
	_c.Call.Return(run)
	return _c
}
