// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockeryMessage creates a new instance of MockeryMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockeryMessage[V any, M any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockeryMessage[V, M] {
	mock := &MockeryMessage[V, M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockeryMessage is an autogenerated mock type for the Message type
type MockeryMessage[V any, M any] struct {
	mock.Mock
}

type MockeryMessage_Expecter[V any, M any] struct {
	mock *mock.Mock
}

func (_m *MockeryMessage[V, M]) EXPECT() *MockeryMessage_Expecter[V, M] {
	return &MockeryMessage_Expecter[V, M]{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockeryMessage
func (_mock *MockeryMessage[V, M]) Accept(ctx context.Context, visitor V) (M, error) {
	ret := _mock.Called(ctx, visitor)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 M
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, V) (M, error)); ok {
		return returnFunc(ctx, visitor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, V) M); ok {
		r0 = returnFunc(ctx, visitor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(M)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, V) error); ok {
		r1 = returnFunc(ctx, visitor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockeryMessage_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockeryMessage_Accept_Call[V any, M any] struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - visitor V
func (_e *MockeryMessage_Expecter[V, M]) Accept(ctx interface{}, visitor interface{}) *MockeryMessage_Accept_Call[V, M] {
	return &MockeryMessage_Accept_Call[V, M]{Call: _e.mock.On("Accept", ctx, visitor)}
}

func (_c *MockeryMessage_Accept_Call[V, M]) Run(run func(ctx context.Context, visitor V)) *MockeryMessage_Accept_Call[V, M] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 V
		if args[1] != nil {
			arg1 = args[1].(V)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockeryMessage_Accept_Call[V, M]) Return(v M, err error) *MockeryMessage_Accept_Call[V, M] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockeryMessage_Accept_Call[V, M]) RunAndReturn(run func(ctx context.Context, visitor V) (M, error)) *MockeryMessage_Accept_Call[V, M] {
	_c.Call.Return(run)
	return _c
}
