// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockinterfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yeluyang/gopkg/stream/interfaces"
)

// NewMockerySource creates a new instance of MockerySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockerySource[V any, M any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockerySource[V, M] {
	mock := &MockerySource[V, M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockerySource is an autogenerated mock type for the Source type
type MockerySource[V any, M any] struct {
	mock.Mock
}

type MockerySource_Expecter[V any, M any] struct {
	mock *mock.Mock
}

func (_m *MockerySource[V, M]) EXPECT() *MockerySource_Expecter[V, M] {
	return &MockerySource_Expecter[V, M]{mock: &_m.Mock}
}

// Next provides a mock function for the type MockerySource
func (_mock *MockerySource[V, M]) Next(ctx context.Context) ([]interfaces.Message[V, M], bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 []interfaces.Message[V, M]
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]interfaces.Message[V, M], bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []interfaces.Message[V, M]); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Message[V, M])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockerySource_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockerySource_Next_Call[V any, M any] struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockerySource_Expecter[V, M]) Next(ctx interface{}) *MockerySource_Next_Call[V, M] {
	return &MockerySource_Next_Call[V, M]{Call: _e.mock.On("Next", ctx)}
}

func (_c *MockerySource_Next_Call[V, M]) Run(run func(ctx context.Context)) *MockerySource_Next_Call[V, M] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockerySource_Next_Call[V, M]) Return(messages []interfaces.Message[V, M], b bool, err error) *MockerySource_Next_Call[V, M] {
	_c.Call.Return(messages, b, err)
	return _c
}

func (_c *MockerySource_Next_Call[V, M]) RunAndReturn(run func(ctx context.Context) ([]interfaces.Message[V, M], bool, error)) *MockerySource_Next_Call[V, M] {
	_c.Call.Return(run)
	return _c
}
